CLASS z2ui5_cl_draft_test_receive_f DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z2ui5_cl_draft_test_receive_f IMPLEMENTATION.
ENDCLASS.
